version: "3.8"

services:
    postgres-compose:
      container_name: teach_crafter_database_container
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=teach_crafter