version: "3.8"

services:
    postgres-compose:
      container_name: teach_crafter_database_container
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=teach_crafter